version: "2"

services:
  cpdevbot:
    container_name: cpdev-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/home/www/public
      - ./logs:/home/www/logs
    env_file: ./server.env
    ports:
      - "7432:7432"
    links:
      - mongodb
      - redisdb
    networks:
      - cpdbotnetwork
  mongodb:
    container_name: cpdev-bot-db
    image: mongo
    volumes:
      - ${ENV_FOLDER}/db:/data/db
    ports:
      - "27432:27017"
    env_file: ./mongo.env
    networks:
      - cpdbotnetwork
  redisdb:
    container_name: cpdev-bot-redis
    image: redis
    volumes:
      - ${ENV_FOLDER}/redis:/data/db
    ports:
      - "6432:6379"
    networks:
      - cpdbotnetwork
networks:
  cpdbotnetwork:
    driver: bridge
